# Generated by Django 4.2.6 on 2023-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_remove_quize_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='Question_id',
            field=models.CharField(max_length=50),
        ),
    ]
