# Generated by Django 4.2.6 on 2023-10-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_alter_quize_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quize',
            name='user_responce',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
