# Generated by Django 4.2.6 on 2023-10-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_quize_user_responce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='user_responce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
