# Generated by Django 4.2.6 on 2023-10-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_alter_quize_user_responce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
