# Generated by Django 4.2.3 on 2023-10-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmath',
            name='istrue',
            field=models.BooleanField(default=False),
        ),
    ]
