# Generated by Django 4.2.6 on 2023-10-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematique', '0002_alter_questionmath_istrue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmath',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='questionmath',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='questionmath',
            name='responce',
        ),
        migrations.RemoveField(
            model_name='questionmath',
            name='signe',
        ),
        migrations.RemoveField(
            model_name='questionmath',
            name='user',
        ),
        migrations.AddField(
            model_name='questionmath',
            name='question',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
