# Generated by Django 4.0.3 on 2023-03-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(choices=[('Admin', 'ADMINISTRATEUR'), ('Autre', 'Autre')], default='Autre', max_length=50),
        ),
    ]
