# Generated by Django 4.2.3 on 2023-10-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poste',
        ),
        migrations.AddField(
            model_name='user',
            name='game_math',
            field=models.BooleanField(default=True),
        ),
    ]
