# Generated by Django 4.2.6 on 2023-10-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_remove_quize_user'),
        ('authentification', '0003_remove_user_poste_user_game_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='questions_repondues',
            field=models.ManyToManyField(blank=True, to='quizApp.quize'),
        ),
    ]
