# Generated by Django 4.2.6 on 2023-10-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematique', '0003_remove_questionmath_num1_remove_questionmath_num2_and_more'),
        ('authentification', '0004_user_questions_repondues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_math',
        ),
        migrations.AddField(
            model_name='user',
            name='game_math',
            field=models.ManyToManyField(blank=True, to='mathematique.questionmath'),
        ),
    ]
