# Generated by Django 4.2.6 on 2023-10-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_remove_user_game_math_user_game_math'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Participations',
                'verbose_name_plural': 'Participationss',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='participation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.participations'),
        ),
    ]
