# Generated by Django 4.2.6 on 2023-10-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_participations_user_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='participation',
        ),
        migrations.AddField(
            model_name='user',
            name='participation_math',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Participations',
        ),
    ]
